[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "otcli"
version = "0.1.0"
description = "Odoo Tasks CLI: automate backup, restore and upgrade of Odoo databases."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Héctor Aular", email = "aular.hector.dev@gmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools",
]
dependencies = [
    "docker>=6.1,<8",
    "typer>=0.9.0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "ruff",
    "pre-commit",
]

[project.urls]
"Homepage" = "https://github.com/tu_usuario/odoo_cli_tool"
"Bug Tracker" = "https://github.com/tu_usuario/odoo_cli_tool/issues"

[project.scripts]
otcli = "otcli.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["."]
python_files = "test_*.py"

[tool.ruff]
target-version = "py312"
line-length = 126
fix = true

[tool.ruff.lint]
extend-select = ["F", "B", "C90", "E501", "I", "UP", "SIM", "RET", "RUF"]
extend-safe-fixes = ["UP008"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "I001"]
"__manifest__.py" = ["B018"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]
